"""add processed readings and alerts

Revision ID: 8318b373e1fd
Revises: 
Create Date: 2026-09-21 13:53:44.445514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8318b373e1fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['sensor_readings.event_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_table('processed_readings',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=20), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('dew_point', sa.Float(), nullable=False),
    sa.Column('heat_index', sa.Float(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['sensor_readings.event_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_processed_readings_device_id'), 'processed_readings', ['device_id'], unique=False)
    op.alter_column('sensor_readings', 'device_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_readings', 'device_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_processed_readings_device_id'), table_name='processed_readings')
    op.drop_table('processed_readings')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
